---
Name: sitemap4
#After: 'framework/*', 'cms/*'
---
LaminBarrow\SiteMap4\SiteMapPage:
  hidefrommap:
    ClassName:
      - ErrorPage
      - SiteMapPage
  theme: default
  #theme: slickmap
  autobuildpage: true
SiteTree:
  extensions:
    - SiteMapSiteTreeExtension
